# Generated by Django 2.2.4 on 2019-08-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livraria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=105)),
                ('Nome_do_autor', models.CharField(max_length=70)),
                ('Assunto', models.CharField(max_length=50)),
                ('Editora', models.CharField(max_length=50)),
                ('ISBN', models.CharField(max_length=50)),
                ('Publicacao', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
