# Generated by Django 2.0.6 on 2019-09-05 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_compras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=90)),
                ('textoTitulo', models.CharField(max_length=80)),
                ('preco', models.IntegerField()),
                ('textoAnuncio', models.CharField(max_length=150)),
                ('nomeContato', models.CharField(max_length=60)),
                ('telefone', models.CharField(max_length=20)),
                ('secao', models.CharField(max_length=25)),
                ('tipoAnuncio', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('qtdQuartoss', models.IntegerField()),
                ('proprietario', models.CharField(max_length=80)),
                ('valorCondominio', models.BooleanField()),
            ],
        ),
    ]
